# Generated by Django 3.2 on 2021-05-03 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager_main', '0004_auto_20210503_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_of_creation',
            field=models.DateTimeField(auto_now=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='file',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='task_manager_main.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='commentary',
            field=models.BooleanField(default=False, verbose_name='содержит комментарии'),
        ),
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='C:\\Users\\Postalet\\Desktop\\files\\'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(help_text='имя файла не должно содержать следующих символов: @ ! . % + | > < " ? * : / \\', max_length=260, verbose_name='имя файла'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_begin',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='время начала работ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='время завершения задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_creation',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='время создания задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_manager_main.status'),
        ),
        migrations.CreateModel(
            name='TasksGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('change_text', models.CharField(max_length=80)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager_main.task')),
            ],
        ),
    ]
