# Generated by Django 3.2 on 2021-05-11 06:55

from django.db import migrations, models
import task_manager_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_main', '0006_status_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=task_manager_main.models.file_dir),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=260),
        ),
    ]
