# Generated by Django 3.2 on 2021-06-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_main', '0007_auto_20210511_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksgraph',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='tasksgraph',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='commentary',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TasksGraph',
        ),
    ]
